version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "America/Santo_Domingo"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - frontend

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "08:15"
      timezone: "America/Santo_Domingo"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - backend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: "America/Santo_Domingo"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - ci
